name: "[ACTION] Auto Commit"
# .github/actions/git-commit/action.yml

description: '自动提交并推送指定的 Markdown 文件'

inputs:
  patterns:
    description: '要提交的文件模式列表（每行一个）'
    required: false
    default: |
      **/*.md
      *.md
    
  commit-prefix:
    description: '提交信息的前缀'
    required: false
    default: 'Auto Commit'
  
runs:
  using: composite
  steps:
    - name: "[STEP] Run Git Info via Action"
      uses: ./.github/actions/git-info

    - name: "[STEP] Run Worker via Bash"
      shell: bash
      run: bash ${{ github.action_path }}/worker.bash
      env:
        INPUT_PATTERNS: ${{ inputs.patterns }}
        INPUT_COMMIT_PREFIX: ${{ inputs.commit-prefix }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        ACTION_PATH: ${{ github.action_path }}
    
    - name: "[STEP] Print Summary via Action"
      uses: ./.github/actions/bot-summary
      with:
        title: "Git Commit"
        message: "${{ env.COMMIT_STATUS }}"
        