name: 口服调节
description: 记录口服药物信息
title: "口服调节"
labels: ["adjust"]

body:
  - type: checkboxes
    id: today
    attributes:
      label: 今日
      options:
        - label: 今日
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: 日期
      description: 若今日已勾选，请忽略此项
      placeholder: 请输入日期 (例如 2026-04-01)

  - type: dropdown
    id: anastrozole
    attributes:
      label: 阿那曲唑（每片1毫克）
      options: ["0片", "1片", "2片", "3片",
        "4片", "5片", "6片", "7片", "8片", "9片"]
    validations:
      required: true

  - type: dropdown
    id: letrozole
    attributes:
      label: 来曲唑 (每片2.5毫克)
      options: ["0片", "1片", "2片", "3片", 
        "4片", "5片", "6片", "7片", "8片", "9片"]
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"

  - type: dropdown
    id: effect
    attributes:
      label: 效果
      options: ["正常", "跳过"]
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: 说明
      placeholder: 在此输入补充说明