name: 注射调节
description: 记录注射调节信息
title: 注射调节
labels: ["adjust"]
body:
  - type: checkboxes
    id: today
    attributes:
      label: 今日
      options:
        - label: 今日
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: 日期
      description: 若今日已勾选，请忽略此项
      placeholder: 请输入日期 (例如 2026-04-01)

  - type: dropdown
    id: anastrozole
    attributes:
      label: 阿那曲唑
      options: ["0片", "1片", "2片", "3片", "4片", "5片", "6片", "7片", "8片", "9片"]
    validations:
      required: true

  - type: dropdown
    id: letrozole
    attributes:
      label: 来曲唑 (每片2.5毫克)
      options: ["0片", "1片", "2片", "3片", "4片", "5片", "6片", "7片", "8片", "9片"]
    validations:
      required: true

  - type: dropdown
    id: testosterone
    attributes:
      label: 丙酸睾酮 (每支25毫克)
      options: ["0支", "1支", "2支", "3支", "4支", "5支", "6支", "7支", "8支", "9支"]
    validations:
      required: true

  - type: dropdown
    id: hcg
    attributes:
      label: 绒促性素 (每支500单位)
      options: ["0支", "1支", "2支", "3支", "4支", "5支", "6支", "7支", "8支", "9支"]
    validations:
      required: true
  -
   type: markdown
    attributes:
      value: "### 注射详情"

  - type: input
    id: injection_site
    attributes:
      label: 注射部位
      placeholder: 请输入注射部位
    validations:
      required: true

  - type: input
    id: push_site
    attributes:
      label: 推药部位
      placeholder: 请输入推药部位
    validations:
      required: true

  - type: dropdown
    id: massage_minutes
    attributes:
      label: 按揉时长
      options: ["按揉0分钟片", "按揉1分钟片", "按揉2分钟片", "按揉3分钟",
       "按揉4分钟片", "按揉5分钟片", "按揉6分钟片", "按揉7分钟片", "按揉8分钟片", "按揉9分钟"]
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"

  - type: dropdown
    id: effect
    attributes:
      label: 效果
      options: ["正常", "明显溢出", "轻微溢出"]
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: 说明
      placeholder: 可选补充说明