name: "[ACTION] Git Info"
# .github/actions/git-info/action.yml

description: Load Git Info

runs:
  using: composite
  steps:
    - name: "[STEP] Run Worker via Bash"
      run: bash ${{ github.action_path }}/worker.bash
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}

    - name: "[STEP] Print Summary via Action"
      uses: ./.github/actions/bot-summary
      with:
        title: "Git Info"
        message: "Loaded ${{ env.CONFIG_COUNT }} Configurations."