name: "[WORKFLOW] Issue Opened"
# .github/workflow/adjust-opened.yml

on:
 issues:
    types: [opened, edited]

jobs:
  issue-opened:
    if: contains(github.event.issue.labels.*.name, 'adjust')
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: "[STEP] Run Checkout Repository via Action"
        uses: actions/checkout@main

      - name: "[Step] Run Issue Parser via Action"
        id: parser
        uses: stefanbuck/github-issue-parser@main

      - name: "[STEP] Run Issue Date via Action"
        id: issue-date
        uses: ./.github/actions/adjust-date
        with:
          input_date: ${{ steps.parser.outputs.issueparser_date }}
          is_today: ${{ steps.parser.outputs.issueparser_today }}

      - name: debug-success
        if: success()
        run: echo ${{ steps.issue-date.outputs.date }} >> $GITHUB_STEP_SUMMARY

      - name: debug-failure
        if: failure()
        run: echo "ERROR-on-Issue-Date" >> $GITHUB_STEP_SUMMARY