name: "[WORKFLOW] Create Directories"
# .github/workflows/create-dirs.yml

on:
  workflow_dispatch:
    inputs:
      date:
        description: '请输入日期 (YYYY-MM-DD)，不填则使用当前日期'
        required: false

jobs:
  create-dirs:
    runs-on: ubuntu-latest
    steps:
      - name: "[STEP] Run Checkout Repository via Action"
        uses: actions/checkout@main

      - name: "[STEP] Run Create Directories Via Action"
        uses: ./.github/actions/create-dirs
        with:
          date: ${{ github.event.inputs.date }}

      - name: "[STEP] Run Git Commit via Action"
        uses: ./.github/actions/git-commit
        with:
          patterns: |
            **/*
          commit-prefix: "Create Directories"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}