name: "[WORKFLOW] Git Info"
# .github/workflow/git-info.yml

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  git-info:
    runs-on: ubuntu-latest

    steps:
      - name: "[STEP] Run Checkout Repository via Action"
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "[STEP] Run Auto Dependencies via Action"
        uses: ./.github/actions/auto-deps
        
      - name: "[STEP] Run Git Info via Action"
        uses: ./.github/actions/git-info
        
      - name: "[STEP] Verify Git Config via Command"
        run: git config --local --list
        shell: bash
        