name: "[WORKFLOW] Git Commit"
# .github/workflow/git-commit.yml

on: 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  git-commit:
    runs-on: ubuntu-latest

    steps:
      - name: "[STEP] Run Checkout Repository via Action"
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "[STEP] Run Auto Dependencies via Action"
        uses: ./.github/actions/auto-deps          
          
      - name: "[STEP] Run Auto Commit via Action"
        uses: ./.github/actions/git-commit
        with:
          patterns: |
            **/*
          commit-prefix: "Git Commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}